### ISSUE TITLE
Missing Documentation for Running the Project Locally

### ISSUE THREAD

**Issue by adibahsan** [thehexcodehq/flicker-tv#2]
### Description
The current project lacks documentation on how to set up and run it in a development environment. This is crucial for contributors and users who want to test and develop on their local machines.

### Expected Behavior
There should be clear and comprehensive documentation explaining the steps required to set up and run the project in a development environment.

### Steps to Reproduce
1. Navigate to the project repository: [HexCodeHQ/flicker-tv](https://github.com/HexCodeHQ/flicker-tv/)
2. Look for documentation on setting up the project locally.

### Actual Behavior
No documentation is available regarding the process of running the project in a local development environment.

### Additional Information
- Operating System: [Specify your operating system, e.g., Windows 10, macOS, Linux]
- Node.js version: [Specify your Node.js version, e.g., v14.17.0]

### Proposed Solution
Include a comprehensive guide in the README.md or a separate document, explaining the steps to set up and run the project locally.

### Priority
This issue is of high priority, as it hinders the ability of contributors and users to actively engage with and contribute to the project.

**Comment by sorenblank** [comment]
@adibahsan We will look into it Adib. Thanks for mentioning it.

**Comment by sorenblank** [comment]
@adibahsan Resolved the issue with this PR #7 and closing this Issue. Thanks for your contribution.
